import 'package:recase/recase.dart';

import '../generators/model_generator.dart';

/// Templates for model generation
class ModelTemplates {
  /// Model class template with JSON serialization
  static String modelDart(String modelName, List<ModelField> fields) {
    final rc = ReCase(modelName);
    final className = rc.pascalCase;

    final fieldDeclarations =
        fields.map((f) => '  final ${f.dartType} ${f.name};').join('\n');

    final constructorParams = fields.map((f) {
      if (f.isNullable) {
        return '    this.${f.name},';
      } else {
        return '    required this.${f.name},';
      }
    }).join('\n');

    // empty() factory — all fields get sensible zero values
    final emptyArgs = fields.map((f) {
      if (f.isNullable) return '      ${f.name}: null,';
      return '      ${f.name}: ${_defaultValue(f)},';
    }).join('\n');

    final copyWithParams =
        fields.map((f) => '    ${_nullableType(f)} ${f.name},').join('\n');
    final copyWithBody = fields
        .map((f) => '      ${f.name}: ${f.name} ?? this.${f.name},')
        .join('\n');

    final fromJsonBody =
        fields.map((f) => _generateFromJsonField(f)).join('\n');
    final toJsonBody =
        fields.map((f) => _generateToJsonField(f)).join('\n');

    final equalsBody = fields
        .map((f) => '          ${_equalsExpr(f)}')
        .join(' &&\n');
    final hashCodeBody = fields.map((f) => f.name).join(', ');
    final toStringBody =
        fields.map((f) => '${f.name}: \$${f.name}').join(', ');

    final hasListField = fields.any((f) => f.type.startsWith('List<'));

    // Build imports
    final imports = StringBuffer();
    imports.writeln("import 'dart:convert';");
    if (hasListField) {
      imports.writeln("import 'package:flutter/foundation.dart';");
    }

    return '''
$imports
/// $className model class
///
/// Generated by Neuron CLI — `neuron generate model $modelName`
class $className {
  const $className({
$constructorParams
  });

  /// Create an empty $className with default values.
  factory $className.empty() => $className(
$emptyArgs
      );

$fieldDeclarations

  /// Create a copy with modified fields.
  $className copyWith({
$copyWithParams
  }) => $className(
$copyWithBody
    );

  /// Create from JSON map.
  factory $className.fromJson(Map<String, dynamic> json) => $className(
$fromJsonBody
      );

  /// Create a list from a JSON array.
  static List<$className> fromJsonList(List<dynamic> list) =>
      list.map((e) => $className.fromJson(e as Map<String, dynamic>)).toList();

  /// Create from a JSON string.
  factory $className.fromJsonString(String source) =>
      $className.fromJson(json.decode(source) as Map<String, dynamic>);

  /// Convert to JSON map.
  Map<String, dynamic> toJson() => {
$toJsonBody
      };

  /// Convert to JSON string.
  String toJsonString() => json.encode(toJson());

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is $className &&
$equalsBody;

  @override
  int get hashCode => Object.hash($hashCodeBody);

  @override
  String toString() => '$className($toStringBody)';
}
''';
  }

  // ── fromJson helpers ──────────────────────────────────────────

  static String _generateFromJsonField(ModelField field) {
    final key = "'${field.name}'";
    final q = field.isNullable ? '?' : '';

    switch (field.type) {
      case 'int':
        return '        ${field.name}: json[$key] as int$q,';
      case 'double':
        return field.isNullable
            ? '        ${field.name}: (json[$key] as num?)?.toDouble(),'
            : '        ${field.name}: (json[$key] as num).toDouble(),';
      case 'bool':
        return '        ${field.name}: json[$key] as bool$q,';
      case 'String':
        return '        ${field.name}: json[$key] as String$q,';
      case 'DateTime':
        return field.isNullable
            ? '        ${field.name}: json[$key] != null ? DateTime.parse(json[$key] as String) : null,'
            : '        ${field.name}: DateTime.parse(json[$key] as String),';
      default:
        // List<T>
        if (field.type.startsWith('List<')) {
          final inner = field.type.substring(5, field.type.length - 1);
          return _generateListFromJson(field, inner);
        }
        // Map<String, dynamic> passthrough
        if (field.type == 'Map<String, dynamic>') {
          return field.isNullable
              ? '        ${field.name}: json[$key] as Map<String, dynamic>?,'
              : '        ${field.name}: Map<String, dynamic>.from(json[$key] as Map),';
        }
        // Nested model
        return field.isNullable
            ? '        ${field.name}: json[$key] != null ? ${field.type}.fromJson(json[$key] as Map<String, dynamic>) : null,'
            : '        ${field.name}: ${field.type}.fromJson(json[$key] as Map<String, dynamic>),';
    }
  }

  static String _generateListFromJson(ModelField field, String innerType) {
    final key = "'${field.name}'";
    final cast = _isPrimitive(innerType) ? '(e) => e as $innerType' : '(e) => $innerType.fromJson(e as Map<String, dynamic>)';

    if (field.isNullable) {
      return '        ${field.name}: (json[$key] as List?)?.map($cast).toList(),';
    }
    return '        ${field.name}: (json[$key] as List).map($cast).toList(),';
  }

  // ── toJson helpers ────────────────────────────────────────────

  static String _generateToJsonField(ModelField field) {
    final key = "'${field.name}'";
    final val = field.name;
    final q = field.isNullable ? '?' : '';

    switch (field.type) {
      case 'int':
      case 'double':
      case 'bool':
      case 'String':
        return '        $key: $val,';
      case 'DateTime':
        return '        $key: $val$q.toIso8601String(),';
      default:
        // List<T>
        if (field.type.startsWith('List<')) {
          final inner = field.type.substring(5, field.type.length - 1);
          if (_isPrimitive(inner)) {
            return '        $key: $val,';
          }
          return '        $key: $val$q.map((e) => e.toJson()).toList(),';
        }
        // Map<String, dynamic> passthrough
        if (field.type == 'Map<String, dynamic>') {
          return '        $key: $val,';
        }
        // Nested model
        return '        $key: $val$q.toJson(),';
    }
  }

  // ── Equality helpers ──────────────────────────────────────────

  static String _equalsExpr(ModelField field) {
    // For List fields use listEquals-equivalent
    if (field.type.startsWith('List<')) {
      return 'listEquals(${field.name}, other.${field.name})';
    }
    return '${field.name} == other.${field.name}';
  }

  // ── copyWith nullable wrapper ─────────────────────────────────

  /// For copyWith, all params must be nullable so the caller can omit any.
  static String _nullableType(ModelField field) {
    if (field.isNullable || field.type.endsWith('?')) return field.dartType;
    return '${field.type}?';
  }

  // ── Default values for empty() ────────────────────────────────

  static String _defaultValue(ModelField field) {
    switch (field.type) {
      case 'int':
        return '0';
      case 'double':
        return '0.0';
      case 'bool':
        return 'false';
      case 'String':
        return "''";
      case 'DateTime':
        return 'DateTime(0)';
      default:
        if (field.type.startsWith('List<')) return 'const []';
        if (field.type.startsWith('Map<')) return 'const {}';
        return '${field.type}.empty()';
    }
  }

  // ── Primitive check ───────────────────────────────────────────

  static bool _isPrimitive(String type) =>
      const {'int', 'double', 'bool', 'String', 'num', 'dynamic'}.contains(type);
}
